version: 0.2

env:
  parameter-store:
    # REACT_APP_BASE_API_URL: $/testerwidgets/ui/prod/base-api-url
    REACT_APP_BASE_API_URL: /testerwidgets/ui/prod/base-api-url
    DISTRIBUTION_ID: /testerwidgets/ui/prod/distribution-id

phases:

  install:
    commands:
      - npm install    

  # pre_build:
  #   commands:
      # - echo "$PARAMETER_STORE_NAME" > .env
      # - echo "$PARAMETER_STORE_NAME" > .test
      # - echo "$PARAMETER_STORE_NAME" > .env.production

  build:
    commands:
      - npm run-script build

  post_build:
    commands:
      # TODO: We need to invalidate the cache on deploy
      - aws cloudfront create-invalidation --distribution-id=$DISTRIBUTION_ID --paths '/*'
      
artifacts:
  files:
    - '**/*'
  base-directory: 'build'