export enum EnumWidgetId {
    AUSTRALIAN_COMPANY_NUMBER_GENERATOR = "1",
    AUSTRALIAN_COMPANY_NUMBER_VALIDATOR = "2",
    AUSTRALIAN_TAX_FILE_NUMBER_GENERATOR = "3",
    AUSTRALIAN_TAX_FILE_NUMBER_VALIDATOR = "4",
}