# Cobbled together from: https://github.com/aws-samples/amazon-cloudfront-secure-static-site/tree/master/templates
# Create stack: `aws cloudformation create-stack --stack-name cloudfront-and-s3-01 --region us-east-2 --on-failure DELETE --template-body file://./main.yml --parameters file://./parameters.json --capabilities CAPABILITY_AUTO_EXPAND`
# Step 1) Create a bucket for deployments: aws s3 mb s3://cloudfront-and-s3-01-deployment --region us-east-1
#
# Step 2) Package the deployment:
# aws --region us-east-1 cloudformation package \
#    --template-file main.yml \
#    --s3-bucket cloudfront-and-s3-01-deployment-v2 \
#    --output-template-file packaged.template
#
# Step 3) Deploy:
# aws cloudformation deploy \
#     --region us-east-1 \
#     --parameter-overrides file://./parameters.json \
#     --template-file packaged.template \
#     --stack-name cloudfront-and-s3-01 \
#     --capabilities CAPABILITY_AUTO_EXPAND
#
# View deployment events:
# Step 4) aws cloudformation describe-stack-events --stack-name cloudfront-and-s3-01 --output yaml
#
AWSTemplateFormatVersion: 2010-09-09
Description: TesterWidgets set for https site and cloudfront ditribution.

Parameters:
  SubDomain:
    Description: The part of a website address before your DomainName - e.g. www or img
    Type: String
    Default: www
    AllowedPattern: ^[^.]*$
  DomainName:
    Description: The part of a website address after your SubDomain - e.g. example.com
    Type: String
  HostedZoneId:
    Description: HostedZoneId for the domain e.g. Z23ABC4XYZL05B
    Type: String
  CreateApex:
    Description: Create an Apex Alias in CloudFront distribution - yes/no
    Type: String
    Default: 'no'
    AllowedValues: ['yes','no']
  CertificateArn:
    Description: This is the certicate arn for cloudfront. See 00-cloudfront-and-s3.
    Type: String

Resources:
  
  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./s3-bucket.yaml
      Parameters:
        DomainName: !Ref DomainName


  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudfront-site.yml
      Parameters:
        CertificateArn: !Ref CertificateArn
        DomainName: !Ref DomainName
        SubDomain: !Ref SubDomain
        CreateApex: !Ref CreateApex
        S3BucketRoot: !GetAtt S3BucketStack.Outputs.S3BucketRoot
        S3BucketRootName: !GetAtt S3BucketStack.Outputs.S3BucketRootName
        S3BucketRootArn: !GetAtt S3BucketStack.Outputs.S3BucketRootArn
        S3BucketWww: !GetAtt S3BucketStack.Outputs.S3BucketWww
        S3BucketWwwName: !GetAtt S3BucketStack.Outputs.S3BucketWwwName
        S3BucketWwwArn: !GetAtt S3BucketStack.Outputs.S3BucketWwwArn

Outputs:
  S3BucketRoot:
    Description: Website bucket
    Value: !GetAtt S3BucketStack.Outputs.S3BucketRoot
  S3BucketRootName:
    Description: Website bucket name
    Value: !GetAtt S3BucketStack.Outputs.S3BucketRootName
  CertificateArn:
    Description: Issued certificate
    Value: !Ref CertificateArn
  CFDistributionName:
    Description: CloudFront distribution
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDistribution
  CloudFrontDomainName:
    Description: Website address
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDomainName