# Cobbled together from: https://github.com/aws-samples/amazon-cloudfront-secure-static-site/tree/master/templates
# Create stack: `aws cloudformation create-stack --stack-name cloudfront-and-s3-01 --region us-east-2 --on-failure DELETE --template-body file://./main.yml --parameters file://./parameters.json --capabilities CAPABILITY_AUTO_EXPAND`
AWSTemplateFormatVersion: 2010-09-09
Description: TesterWidgets set for https site and cloudfront ditribution.

Metadata:
  # AWS::CloudFormation::Interface:
  #   ParameterGroups:
  #     - Label:
  #         default: Domain
  #       Parameters:
  #         - SubDomain
  #         - DomainName

# Mappings:
#   Solution:
#     Constants:
#       Version: 'v0.7'

# Rules:
#   OnlyUsEast1:
#     Assertions:
#       - Assert:
#           Fn::Equals:
#             - !Ref AWS::Region
#             - us-east-1
#         AssertDescription: |
#           This template can only be deployed in the us-east-1 region.
#           This is because the ACM Certificate must be created in us-east-1

Parameters:
  SubDomain:
    Description: The part of a website address before your DomainName - e.g. www or img
    Type: String
    Default: www
    AllowedPattern: ^[^.]*$
  DomainName:
    Description: The part of a website address after your SubDomain - e.g. example.com
    Type: String
  HostedZoneId:
    Description: HostedZoneId for the domain e.g. Z23ABC4XYZL05B
    Type: String
  CreateApex:
    Description: Create an Apex Alias in CloudFront distribution - yes/no
    Type: String
    Default: 'no'
    AllowedValues: ['yes','no']
  CertificateArn:
    Description: This is the certicate arn for cloudfront. See 00-cloudfront-and-s3.
    Type: String

Resources:
  # Check if we even need this or if it's just for uploading the site
  # CustomResourceStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ./custom-resource.yaml
  #     Parameters:
  #       CertificateArn: !Ref CertificateArn
  #       DomainName: !Ref DomainName
  #       SubDomain: !Ref SubDomain
  #       CreateApex: !Ref CreateApex

  # We don't need this I don't think, use previous step.
  # AcmCertificateStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ./acm-certificate.yaml
  #     Parameters:
  #       SubDomain: !Ref SubDomain
  #       DomainName: !Ref DomainName
  #       CreateApex: !Ref CreateApex
  #       HostedZoneId: !Ref HostedZoneId
  #     Tags:
  #       - Key: Solution
  #         Value: ACFS3

  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./s3-bucket.yml
      # Parameters:
      #   CertificateArn: !Ref CertificateArn
      #   DomainName: !Ref DomainName
      #   SubDomain: !Ref SubDomain
      #   CreateApex: !Ref CreateApex


  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudfront-site.yml
      Parameters:
        CertificateArn: !Ref CertificateArn
        DomainName: !Ref DomainName
        SubDomain: !Ref SubDomain
        CreateApex: !Ref CreateApex
        S3BucketRoot: !GetAtt S3BucketStack.Outputs.S3BucketRoot
        S3BucketRootName: !GetAtt S3BucketStack.Outputs.S3BucketRootName
        S3BucketRootArn: !GetAtt S3BucketStack.Outputs.S3BucketRootArn
        # S3BucketLogs: !GetAtt CustomResourceStack.Outputs.S3BucketLogs
        # S3BucketLogsName: !GetAtt CustomResourceStack.Outputs.S3BucketLogsName

Outputs:
  # SolutionVersion:
  #   Value: !FindInMap [Solution, Constants, Version]
  # CopyFunction:
  #   Description: S3 helper function
  #   Value: !GetAtt CustomResourceStack.Outputs.CopyFunction
  # S3BucketLogs:
  #   Description: Logging bucket
  #   Value: !GetAtt CustomResourceStack.Outputs.S3BucketLogs
  S3BucketRoot:
    Description: Website bucket
    Value: !GetAtt S3BucketStack.Outputs.S3BucketRoot
  # S3BucketLogsName:
  #   Description: Logging bucket name
  #   Value: !GetAtt CustomResourceStack.Outputs.S3BucketLogsName
  S3BucketRootName:
    Description: Website bucket name
    Value: !GetAtt S3BucketStack.Outputs.S3BucketRootName
  CertificateArn:
    Description: Issued certificate
    Value: !GetRef CertificateArn
  CFDistributionName:
    Description: CloudFront distribution
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDistribution
  CloudFrontDomainName:
    Description: Website address
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDomainName