# https://github.com/aws-samples/amazon-cloudfront-secure-static-site/blob/master/templates/custom-resource.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket for cloudfront
Transform: AWS::Serverless-2016-10-31

Parameters:
  SubDomain:
    Description: The part of a website address before your DomainName - e.g. www or img
    Type: String
    Default: www
    AllowedPattern: ^[^.]*$
  DomainName:
    Description: The part of a website address after your SubDomain - e.g. example.com
    Type: String

Resources:

  S3BucketRoot:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  S3BucketWww:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${SubDomain}.${DomainName}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

Outputs:
  S3BucketRoot:
    Description: Website bucket
    Value: !Ref S3BucketRoot
  S3BucketRootName:
    Description: Website bucket name
    Value: !GetAtt S3BucketRoot.DomainName
  S3BucketRootArn:
    Description: Website bucket locator
    Value: !GetAtt S3BucketRoot.Arn
  S3BucketWww:
    Description: Www website bucket
    Value: !Ref S3BucketWww
  S3BucketWwwName:
    Description: Www website bucket name
    Value: !GetAtt S3BucketWww.DomainName
  S3BucketWwwArn:
    Description: Www website bucket locator
    Value: !GetAtt S3BucketWww.Arn
    