# https://github.com/aws-samples/amazon-cloudfront-secure-static-site/blob/master/templates/custom-resource.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket for cloudfront
Transform: AWS::Serverless-2016-10-31

# Parameters:
#   SubDomain:
#     Description: The part of a website address before your DomainName - e.g. www or img
#     Type: String
#     Default: www
#     AllowedPattern: ^[^.]*$
#   DomainName:
#     Description: The part of a website address after your SubDomain - e.g. example.com
#     Type: String
#   HostedZoneId:
#     Description: HostedZoneId for the domain e.g. Z23ABC4XYZL05B
#     Type: String
#   CreateApex:
#     Description: Create an Apex Alias in CloudFront distribution - yes/no
#     Type: String
#     Default: 'no'
#     AllowedValues: ['yes','no']

Resources:

  # CopyCustomResource:
  #   Type: "AWS::CloudFormation::CustomResource"
  #   Properties:
  #     ServiceToken: !GetAtt CopyFunction.Arn

  # S3BucketLogs:
  #   Type: AWS::S3::Bucket
  #   DeletionPolicy: Retain
  #   Properties:
  #     AccessControl: LogDeliveryWrite
  #     BucketEncryption:
  #       ServerSideEncryptionConfiguration:
  #         - ServerSideEncryptionByDefault:
  #             SSEAlgorithm: AES256

  S3BucketRoot:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # LoggingConfiguration:
      #   DestinationBucketName: !Ref 'S3BucketLogs'
      #   LogFilePrefix: 'origin/'

  # CopyLayerVersion:
  #   Type: "AWS::Serverless::LayerVersion"
  #   Properties:
  #     ContentUri: ../witch.zip
  #     CompatibleRuntimes:
  #       - nodejs12.x

Outputs:
  S3BucketRoot:
    Description: Website bucket
    Value: !Ref S3BucketRoot
  S3BucketRootName:
    Description: Website bucket name
    Value: !GetAtt S3BucketRoot.DomainName
  S3BucketRootArn:
    Description: Website bucket locator
    Value: !GetAtt S3BucketRoot.Arn
  # S3BucketLogs:
  #   Description: Logging bucket
  #   Value: !Ref S3BucketLogs
  # S3BucketLogsName:
  #   Description: Logging bucket Name
  #   Value: !GetAtt S3BucketLogs.DomainName
  # CopyFunction:
  #   Description: S3 helper function
  #   Value: !GetAtt CopyFunction.Arn